# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreementGen', '0002_auto_20160111_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plan_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_joined',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agreementGen.Plan'),
        ),
    ]
