# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreementGen', '0004_auto_20160130_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
