# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreementGen', '0005_auto_20160130_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
    ]
