# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreementGen', '0006_customer_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middle_name',
        ),
    ]
